sudo: false
language: c

matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3,libgc-dev],sources: [hvr-ghc]}}


before_install:
# stack
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export STACK_FLAGS='-j 2 --no-terminal --skip-ghc-check'
- stack ${STACK_FLAGS} setup

script:
- stack test --test-arguments "--catch-stderr"
- stack test --test-arguments "--catch-stderr --sixten-args -O2"

cache:
  directories:
  - $HOME/.stack
